version: "3"

services:
  redis:
    image: redis:latest
    restart: on-failure
    expose:
      - "6379"

  db:
    image: postgres:16-alpine
    restart: on-failure
    env_file:
      - .dokenv
    expose:
      - "5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "-c", "pg_isready -U $POSTGRES_USER"]
      interval: 10s
      retries: 5
      timeout: 5s

  app:
    build: .
    tty: true
    ports:
      - "8000:8000"
    command: sh -c "alembic - alembic init migrations && alembic revision --autogenerate -m 'Database create' && alembic upgrade head && uvicorn main:main_app --reload "
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    env_file:
      - .dokenv

  celery:
    build: .
    tty: true
    command: celery -A celery_app worker --loglevel=info -P eventlet
    restart: on-failure
    env_file:
      - .dokenv
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app

  celery-beat:
    build: .
    tty: true
    command: celery -A celery_app beat --loglevel=info
    restart: on-failure
    env_file:
      - .dokenv
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
      - app

volumes:
  pg_data: